In [2]:
import numpy as np

In [3]:
#51.创建表示位置(x, y)和颜色(r, g, b, a)的结构化数组
Z = np.zeros(10,[('position',[('x',float),
                             ('y',float)]),
                ('color',[('r',float),
                         ('g',float),
                         ('b',float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [6]:
#52.思考形状为(100, 2)的随机向量，求出点与点之间的距离
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])#取第一列，第二列
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)#T转置，
print(D)

[[0.73445676 0.47960682]
 [0.78863554 0.81332294]
 [0.55593966 0.90380628]
 [0.9378182  0.98847554]
 [0.10602259 0.73570708]
 [0.77036851 0.72368041]
 [0.92693166 0.96091563]
 [0.6773171  0.06559884]
 [0.21515605 0.62982983]
 [0.67090034 0.95431933]
 [0.35668968 0.25821121]
 [0.16561211 0.15189727]
 [0.34699025 0.41346103]
 [0.55302959 0.78350963]
 [0.50852096 0.79938105]
 [0.91639864 0.45548428]
 [0.17876571 0.30879193]
 [0.22028733 0.99145608]
 [0.88998955 0.73265669]
 [0.25451198 0.73750278]
 [0.41975119 0.40733049]
 [0.27812362 0.86302086]
 [0.64611582 0.46450624]
 [0.23662712 0.4881564 ]
 [0.16334628 0.24040056]
 [0.24271194 0.19880707]
 [0.4877473  0.73133443]
 [0.34302055 0.63767618]
 [0.49047311 0.82443793]
 [0.6760025  0.11491099]
 [0.84785716 0.95291437]
 [0.69433468 0.90016422]
 [0.14863283 0.69509395]
 [0.86475895 0.94292314]
 [0.18272354 0.57118253]
 [0.21814538 0.9808911 ]
 [0.145547   0.32042762]
 [0.9484643  0.88530059]
 [0.61005822 0.85931453]
 [0.64301964 0.48821855]


In [8]:
#53.如何将类型为float(32位)的数组类型转换为integer(32位)?
Z = np.arange(10,dtype=np.int32)
print(Z.dtype)
Z = Z.astype(np.float32,copy=False)#astype强制类型转换
print(Z.dtype)
print(Z)

int32
float32
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [11]:
#54.如何读取下面的文件?
"""
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

"""
Z = np.genfromtxt("C:/Users/LiJingzhi/example.txt", delimiter=",")  
#从文本文件加载数据，并按指定处理缺失值。
#delimiter : str, int, or sequence, optional
#用于分隔值的字符串。 默认情况下，任何连续的空格都用作分隔符。 也可以提供整数或整数序列作为每个字段的宽度。
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [16]:
#55.numpy数组枚举(enumerate)的等价操作? 
#在numpy中，np.ndenumerate()效果等同与enumerate，并且支持对多维数据的输出
#np.nindex(*shape)用于求数列中元素的下标
Z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
       print(index,value)
print('*'*40)
for index in np.ndindex(Z.shape):
       print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
****************************************
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [17]:
#56.构造一个二维高斯矩阵
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))#网格
D = np.sqrt(X**2+Y**2)
sigma,mu = 1.0,0.0
G = np.exp(-( (D-mu)**2 / (2.0*sigma**2) ))#返回e的幂次方
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [6]:
#57.如何在二维数组的随机位置放置p个元素?
"""
# 参数意思分别 是从a 中以概率P，随机选择3个, p没有指定的时候相当于是一致的分布
a1 = np.random.choice(a=5, size=3, replace=False, p=None)
print(a1)
# 非一致的分布，会以多少的概率提出来
a2 = np.random.choice(a=5, size=3, replace=False, p=[0.2, 0.1, 0.3, 0.4, 0.0])
print(a2)
# replacement 代表的意思是抽样之后还放不放回去，如果是False的话，那么出来的三个数都不一样，如果是
True的话， 有可能会出现重复的，因为前面的抽的放回去了。
"""
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace = False),1)#随机放在哪个位置
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
#58. 减去矩阵每一行的平均值
X = np.random.rand(5,10)
print(X)
Y = X-X.mean(axis=1,keepdims = True)
"""
axis 不设置值，对 m*n 个数求均值，返回一个实数
axis = 0：压缩行，对各列求均值，返回 1* n 矩阵
axis =1 ：压缩列，对各行求均值，返回 m *1 矩阵
当 keepidms=True,保持其二维或者三维的特性,(结果保持其原来维数)
默认为 False,不保持其二维或者三维的特性.(结果不保持其原来维数)
"""
print(Y)

[[0.113319   0.46095388 0.47139112 0.01180418 0.08217751 0.25514562
  0.38704195 0.030029   0.3207921  0.86745972]
 [0.92064405 0.00491177 0.75509353 0.56745214 0.79204902 0.49791408
  0.44512687 0.49385596 0.00636146 0.64290364]
 [0.06352781 0.87037417 0.55421143 0.18644921 0.13751306 0.14645564
  0.77113647 0.01444729 0.24590113 0.65699602]
 [0.60453956 0.4797786  0.96526048 0.30404036 0.57685752 0.72017627
  0.19076544 0.02182516 0.33283997 0.44542367]
 [0.29559658 0.21404763 0.72056937 0.25907432 0.4154736  0.53438138
  0.92489739 0.11341096 0.95790182 0.86240719]]
[[-0.18669241  0.16094247  0.17137971 -0.28820723 -0.2178339  -0.04486579
   0.08703055 -0.26998241  0.0207807   0.56744831]
 [ 0.40801279 -0.50771949  0.24246228  0.05482089  0.27941777 -0.01471717
  -0.06750438 -0.01877529 -0.50626979  0.13027239]
 [-0.30117342  0.50567295  0.18951021 -0.17825201 -0.22718817 -0.21824558
   0.40643525 -0.35025393 -0.11880009  0.29229479]
 [ 0.14038886  0.01562789  0.50110978 -0.16011034

In [15]:
#59.如何对数组通过第n列进行排序?
Z = np.random.randint(1,10,(3,3))
print(Z)
print(Z[Z[:1].argsort()])#argsort函数返回的是数组值从小到大的索引值

[[5 2 5]
 [9 8 6]
 [6 6 5]]
[[[9 8 6]
  [5 2 5]
  [6 6 5]]]


In [19]:
#60.如何判断一个给定的二维数组存在空列?
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())#any或操作 ~取反

[[0 2 1 1 1 1 0 0 2 2]
 [1 0 2 1 0 1 1 1 2 1]
 [1 1 1 0 1 2 2 0 1 1]]
False


In [23]:
#61.从数组中找出与给定值最接近的值 
Z = np.random.uniform(0,1,10)
z = 0.5
print(Z)
n = np.abs(Z - z).argmin()#返回最小那个值的下标
print(n)
m = Z.flat[n]#flat一维迭代器
print(m)

[0.37497051 0.19497881 0.59224519 0.36459779 0.24836767 0.68477496
 0.92304328 0.72523023 0.04482085 0.35597863]
2
0.5922451916546907


In [34]:
#62.思考形状为(1, 3)和(3, 1)的两个数组形状，如何使用迭代器计算它们的和?
A = np.arange(3).reshape(3, 1)
print(A)
print(B)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])#提供了一种灵活访问一个或者多个数组元素的方式，可控制遍历顺序，修改值
for x, y, z in it:
    z[...] = x + y
    print(z)
print (it.operands[2])
print(it)

[[0]
 [1]
 [2]]
[[0 1 2]]
0
1
2
1
2
3
2
3
4
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [43]:
#63.创建一个具有name属性的数组类
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        #　-类.__new__方法，创建一个对象
        #__new__() 方法是在类准备将自身实例化时调用，静态方法
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
 
Z = NameArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [47]:
#64.给定一个向量，如何让在第二个向量索引的每个元素加1(注意重复索引)? 
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
M = np.bincount(I, minlength=len(Z))#该函数用于统计一个非负的list或array中元素的出现次数,索引是数字，值是出现次数
print(M)
Z += M
print(Z)
 
# Another solution

#np.add.at(Z, I, 1)
#print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[9 9 6 1 1 5 6 1 8 6 9 7 3 0 2 6 8 0 4 0]
[3 3 1 1 1 1 4 1 2 3]
[4. 4. 2. 2. 2. 2. 5. 2. 3. 4.]


In [48]:
#65. 如何根据索引列表I将向量X的元素累加到数组F? 
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [49]:
#66. 思考(dtype = ubyte)的(w, h, 3)图像，计算唯一颜色的值
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))#该函数是去除数组中的重复数字，并进行排序之后输出。
print(np.unique(I))

[0 1]


In [50]:
#67. 思考如何求一个四维数组最后两个轴的数据和
A = np.random.randint(0,10,(3,4,3,4))
# 传递一个元组(numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[72 50 78 42]
 [49 57 31 56]
 [29 47 62 70]]
[[72 50 78 42]
 [49 57 31 56]
 [29 47 62 70]]


In [51]:
#68. 考虑一维向量D，如何使用相同大小的向量S来计算D的子集的均值，其描述子集索引？
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)#如果值n发现在位置i，那么out[n] += weight[i]，加权
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.41851577 0.57820785 0.48784548 0.43165814 0.53139053 0.46674569
 0.69668384 0.53563468 0.50806423 0.48242397]


In [52]:
#69. **如何获得点积的对角线？
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
 
# Slow version  
np.diag(np.dot(A, B))
 
# Fast version
np.sum(A * B.T, axis=1)
 
# Faster version
np.einsum("ij,ji->i", A, B)#这个无敌了

array([1.37157959, 1.20555925, 1.67172895, 0.92068181, 0.92414913])

In [54]:
#70.考虑向量[1,2,3,4,5]，如何建立一个新的向量，在每个值之间交错有3个连续的零？
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z#间隔4
print(Z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [55]:
#71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [56]:
#72.如何对一个数组中任意两行做交换?
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [57]:
#73. 思考描述10个三角形（共享顶点）的一组10个三元组，找到组成所有三角形的唯一线段集
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 6, 33) ( 6, 98) ( 7, 14) ( 7, 91) (10, 19) (10, 20) (11, 18) (11, 74)
 (14, 91) (15, 17) (15, 56) (17, 56) (18, 74) (19, 20) (21, 29) (21, 83)
 (29, 83) (30, 46) (30, 77) (33, 98) (40, 69) (40, 98) (41, 42) (41, 98)
 (42, 98) (46, 77) (51, 51) (51, 67) (69, 98)]


In [58]:
#74. 给定一个二进制的数组C，如何生成一个数组A满足np.bincount(A)==C? 
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [59]:
#75. 如何通过滑动窗口计算一个数组的平均数?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)#计算轴向元素累加和，返回由中间结果组成的数组
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [61]:
#76.思考以为数组Z，构建一个二维数组，其第一行是(Z[0],Z[1],Z[2])， 然后每一行移动一位，最后一行为 (Z[-3],Z[-2],Z[-1]) 

from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)#这个函数可以高效地切分一个数组为不同的shape块，strides跨过多少比特
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [62]:
#77. 如何对布尔值取反，或改变浮点数的符号(sign)?
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)#逻辑非
 
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.27479431, -0.86265647,  0.07454844, -0.34071828,  0.0709865 ,
       -0.48486495, -0.42894764, -0.19982225, -0.37845971,  0.03201124,
       -0.30927772, -0.47202254,  0.89336955,  0.51969405, -0.86348719,
        0.74626594,  0.63014657, -0.95872964,  0.89151132, -0.24582146,
        0.98838914,  0.20853765, -0.087576  , -0.9312713 ,  0.496977  ,
       -0.66870563,  0.90270549, -0.39536655, -0.66245594,  0.15531776,
       -0.40734872,  0.44209032,  0.71623633,  0.98596341, -0.29113406,
       -0.96882842, -0.52157621, -0.84594911, -0.31403889,  0.05395941,
       -0.81899981,  0.48021704, -0.02926814, -0.50069208,  0.13799262,
        0.09308386, -0.13260719, -0.93355698,  0.13785008,  0.6375775 ,
       -0.47467572,  0.022022  ,  0.20666465,  0.10556274,  0.7623558 ,
        0.88787837, -0.437507  , -0.51090759, -0.9443583 , -0.66989822,
        0.8247513 , -0.37687755,  0.00585755, -0.3649649 , -0.06155465,
        0.57310694,  0.04178253, -0.32713499, -0.07885721, -0.09

In [5]:
#78.思考两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)#直线长度
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
print(P0)
P1 = np.random.uniform(-10,10,(10,2))
print(P1)
p  = np.random.uniform(-10,10,( 1,2))
print(p)
print(distance(P0, P1, p))

[[ 7.60325975  5.00013384]
 [ 8.8350963   8.29639175]
 [-3.67559222 -1.39060178]
 [-7.73386105 -2.65194543]
 [-0.61982467 -4.24692918]
 [ 5.52931327 -6.15808776]
 [ 9.54646088  9.43961004]
 [-2.60073776 -6.66736409]
 [-6.35663125  3.68454113]
 [-9.33139196  2.95865916]]
[[-4.04116737  9.68172802]
 [ 6.33471655  8.94035609]
 [-7.26810013  5.35141058]
 [ 3.72340735  2.75459764]
 [ 1.13937616  0.03599233]
 [-0.52908799 -7.10767416]
 [-0.82406239 -2.16314785]
 [ 5.5450559  -1.23585344]
 [-6.16939848 -0.90479825]
 [ 1.78991276  3.85537365]]
[[-7.35422372  7.20923078]]
[ 3.52989191  5.09054728  0.79764982  8.75609352 10.58209465 15.20107851
 11.11462638 14.18247223  0.8530849   4.07791758]


In [6]:
#79. 考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离?
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[16.29393541 15.91462008  7.00233288 15.09921553  6.64493274  1.56128574
  18.44743148 14.40591459  9.76953901 12.87202223]
 [ 5.73962465  5.32316869  1.7468877   9.24912851  4.1692106   2.26317589
   9.73196529  4.53459135  3.5510443   3.35858992]
 [ 3.33903868  4.71965523  1.31325478  5.58771112 13.73157546  0.96318106
   3.00295632  5.22373954  0.48765925  6.20041376]
 [ 0.83342944  2.90284108  4.61782032  2.84905333  8.49752023  7.70130951
   3.61861387  3.34841014  2.85813707  2.63018203]
 [ 0.5677254   4.10134172  9.39616726  1.75741278  9.20618271 13.11353555
   0.31605849  5.5783588   7.34479078  5.21086092]
 [ 0.16783     1.44434588  0.12021377  7.20879946 10.45635443  0.94209017
   5.54509523  2.13140959  1.25014356  3.20479784]
 [ 7.54645935  7.01619656  6.42531598  0.42404391 17.50508361  5.17559047
   2.05769557  6.54129323  5.67344741  7.1511138 ]
 [10.43972222  9.38718895  5.10973505 12.81393721  0.46443975  0.61784249
  14.15077065  8.04343071  7.23763863  6.63207589]


In [7]:
#80.思考一个任意的数组，编写一个函数，该函数提取一个具有固定形状的子部分，并以一个给定的元素为中心(在该部分填充值)
#????????????????????????????????????????????????????????????????????????????????????????????????????????????????
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
 
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
 
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
 
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
 
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 4 0 2 4 3 0 5 4 9]
 [4 6 2 9 3 6 6 8 1 0]
 [3 8 9 6 7 2 5 3 9 9]
 [5 3 7 8 2 4 0 8 9 4]
 [4 4 4 2 2 1 8 7 0 8]
 [9 3 7 4 1 9 2 6 6 5]
 [0 2 7 6 8 7 3 4 6 0]
 [9 4 9 8 0 8 0 4 7 7]
 [1 1 7 5 0 9 1 1 5 2]
 [8 1 0 2 4 8 3 4 8 2]]
[[0 0 0 0 0]
 [0 5 4 0 2]
 [0 4 6 2 9]
 [0 3 8 9 6]
 [0 5 3 7 8]]


<ipython-input-7-4d4c0f1823ba>:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [12]:
#81.考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? 
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))#高效地切分一个数组为不同的shape块
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [13]:
#82. 计算矩阵的秩 
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
"""
函数：np.linalg.svd(a,full_matrices=1,compute_uv=1)
a是一个形如(M,N)矩阵
full_matrices的取值是为0或者1，默认值为1，这时u的大小为(M,M)，v的大小为(N,N) 。否则u的大小为(M,K)，v的大小为(K,N) ，K=min(M,N)。
compute_uv的取值是为0或者1，默认值为1，表示计算u,s,v。为0的时候只计算s。

总共有三个返回值u,s,v
u大小为(M,M)，s大小为(M,N)，v大小为(N,N)。
A = u*s*v
其中s是对矩阵a的奇异值分解。s除了对角元素不为0，其他元素都为0，并且对角元素从大到小排列。s中有n个奇异值，一般排在后面的比较接近0，所以仅保留比较大的r个奇异值。 
"""
rank = np.sum(S > 1e-10)
print(rank)

10


In [14]:
#83. 如何找出数组中出现频率最高的值?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())#统计每个值出现的次数取最大值

6


In [18]:
#84. 从一个10x10的矩阵中提取出连续的3x3区块
Z = np.random.randint(0,5,(10,10))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)#shape读取矩阵的长度,shape[n]表示第n维的长度
print(i)
j = 1 + (Z.shape[1]-3)
print(j)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[2 2 0 4 2 0 4 3 0 2]
 [2 2 4 3 4 1 3 0 3 0]
 [3 4 2 1 2 3 0 0 2 2]
 [1 3 2 3 3 1 1 3 4 0]
 [2 4 1 4 1 4 0 4 0 2]
 [0 3 2 4 2 3 0 0 0 0]
 [1 4 4 2 1 2 0 4 0 4]
 [2 2 0 1 3 3 2 3 3 2]
 [3 1 3 4 2 0 3 0 1 1]
 [4 3 4 4 4 3 3 0 3 3]]
8
8
[[[[2 2 0]
   [2 2 4]
   [3 4 2]]

  [[2 0 4]
   [2 4 3]
   [4 2 1]]

  [[0 4 2]
   [4 3 4]
   [2 1 2]]

  [[4 2 0]
   [3 4 1]
   [1 2 3]]

  [[2 0 4]
   [4 1 3]
   [2 3 0]]

  [[0 4 3]
   [1 3 0]
   [3 0 0]]

  [[4 3 0]
   [3 0 3]
   [0 0 2]]

  [[3 0 2]
   [0 3 0]
   [0 2 2]]]


 [[[2 2 4]
   [3 4 2]
   [1 3 2]]

  [[2 4 3]
   [4 2 1]
   [3 2 3]]

  [[4 3 4]
   [2 1 2]
   [2 3 3]]

  [[3 4 1]
   [1 2 3]
   [3 3 1]]

  [[4 1 3]
   [2 3 0]
   [3 1 1]]

  [[1 3 0]
   [3 0 0]
   [1 1 3]]

  [[3 0 3]
   [0 0 2]
   [1 3 4]]

  [[0 3 0]
   [0 2 2]
   [3 4 0]]]


 [[[3 4 2]
   [1 3 2]
   [2 4 1]]

  [[4 2 1]
   [3 2 3]
   [4 1 4]]

  [[2 1 2]
   [2 3 3]
   [1 4 1]]

  [[1 2 3]
   [3 3 1]
   [4 1 4]]

  [[2 3 0]
   [3 1 1]
   [1 4 0]]

  [[3 0 0]
   [1 1 3]
   [

In [19]:
#85.创建一个满足 Z[i,j] == Z[j,i]的二维数组子类
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  2 11  8  8]
 [ 2  8 10  2  9]
 [11 10  2 42  9]
 [ 8  2 42  7  2]
 [ 8  9  9  2  4]]


In [26]:
#86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)?
p, n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])#?????
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [29]:
#87. 对于一个16x16的数组，如何得到一个区域的和(区域大小为4x4)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
#??????????????????????????????????????????????????????????????????
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [30]:
#88. 如何利用numpy数组实现Game of Life?

In [32]:
#89.如何找到一个数组的第n个最大值?
Z = np.arange(10000)
np.random.shuffle(Z)#shuffle() 方法将序列的所有元素随机排序。
n = 5
# Slow
print (Z[np.argsort(Z)[-n:]])#argsort函数返回的是数组值从小到大的索引值
# Fast
print (Z[np.argpartition(-Z,n)[:n]])
"""
在快排算法中，有一个典型的操作：partition。这个操作指：根据一个数值x，把数组中的元素划分成两半，使得index前面的元素都不大于x，index后面的元素都不小于x。
numpy中的argpartition()函数就是起的这个作用。对于传入的数组a，先用O(n)复杂度求出第k大的数字，然后利用这个第k大的数字将数组a划分成两半。
"""

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


'\n在快排算法中，有一个典型的操作：partition。这个操作指：根据一个数值x，把数组中的元素划分成两半，使得index前面的元素都不大于x，index后面的元素都不小于x。\nnumpy中的argpartition()函数就是起的这个作用。对于传入的数组a，先用O(n)复杂度求出第k大的数字，然后利用这个第k大的数字将数组a划分成两半。\n'

In [33]:
#90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)


In [34]:
#91. 如何从一个常规数组中创建记录数组(record array)? 
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [38]:
#92.思考一个大向量Z, 用三种不同的方法计算它的立方

x = np.random.rand(5e4)
 
np.power(x,3)
x*x*x
np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer